#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Helios.Resource", IsApplication=true)]

namespace Helios
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_overflow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int LayoutOFF = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LayoutOn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ProgressBarStyle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int xs = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000f
			public const int AlarmProgressBar = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int AlarmTextView1 = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int KlikButton1 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int KlikButton2 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int KlikButton3 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int KlikButton4 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int KlikButton5 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int KlikButton6 = 2131165212;
			
			// aapt resource value: 0x7f070010
			public const int KlikLinearLayout1 = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int KlikLinearLayout2 = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int KlikLinearLayout3 = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int KlikLinearLayout4 = 2131165210;
			
			// aapt resource value: 0x7f07001e
			public const int KlikProgressBar = 2131165214;
			
			// aapt resource value: 0x7f070011
			public const int KlikTextView1 = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int KlikTextView2 = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int KlikTextView3 = 2131165209;
			
			// aapt resource value: 0x7f07001d
			public const int KlikTextView4 = 2131165213;
			
			// aapt resource value: 0x7f070002
			public const int arduinoStatus = 2131165186;
			
			// aapt resource value: 0x7f07000e
			public const int button_alarmOff = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int button_alarmOn = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int editIP = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int editPort = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout4 = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout5 = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout6 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout7 = 2131165190;
			
			// aapt resource value: 0x7f070022
			public const int menu = 2131165218;
			
			// aapt resource value: 0x7f07000b
			public const int refreshButton = 2131165195;
			
			// aapt resource value: 0x7f07001f
			public const int sample_main_layout = 2131165215;
			
			// aapt resource value: 0x7f070005
			public const int sensorValueStatus = 2131165189;
			
			// aapt resource value: 0x7f070020
			public const int sliding_tabs = 2131165216;
			
			// aapt resource value: 0x7f070001
			public const int textView4 = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int textView5 = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int textView7 = 2131165188;
			
			// aapt resource value: 0x7f070021
			public const int viewPager = 2131165217;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Frag1Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Frag2Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Frag3Layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int sample_hide_log = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int sample_show_log = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CustomActionBarTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyActionBar = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
